version: '3.8'

services:
  clinicaapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://citacrud:3306/citacrud
      DB_USER_NAME: root
      DB_PASSWORD: 5nA7p496-xQ@
    restart: always
    depends_on:
      citacrud:
        condition: service_healthy
  citacrud:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 5nA7p496-xQ@
      MYSQL_PASSWORD: 5nA7p496-xQ@
      MYSQL_DATABASE: citacrud
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
